version: "2"

services:
  backend-app:
    container_name: "basic-app-backend-app"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "4001:4000"
    depends_on:
      - backend-db

  backend-db:
    container_name: "basic-app-backend-db"
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysqlInit:/docker-entrypoint-initdb.d
    restart: "always"
